id: c6b270b9-bb82-4d6c-a40c-66cd80939c13
name: Product Info
type: composition
data: {}
order: 1250
path: /components/product-info
compositionId: 8fdcb37f-01a2-46ea-9e9e-2b8df0e7551c
pathSegment: product-info
projectMapId: 40535f31-cdc1-4ac3-bb4d-2a008493b431
