# yaml-language-server: $schema=<https://uniform.app/schemas/json-schema/component-definition/v1.json>
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: productInfo
name: Product Info
icon: >-
  https://res.cloudinary.com/uniform-demos/image/upload/v1692281207/csk-icons/component-icons-v2/CSKicon_hero_odv0f6_ipen7r.svg
parameters:
  - id: productKey
    name: Product Key
    type: text
    helpText: ''
    typeConfig: null
    localizable: false
  - id: group_content
    name: Content
    type: group
    typeConfig:
      collapsed: false
      childrenParams:
        - eyebrowText
        - title
        - titleStyle
        - subTitle
        - description
        - highlightText
        - image
        - features
  - id: eyebrowText
    name: Eyebrow text
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig:
      required: false
      multiline: true
      linesCount: '3'
    localizable: true
  - id: titleStyle
    name: Title Style
    type: tp-title-style-parameter
    helpText: ''
    typeConfig: null
  - id: subTitle
    name: Sub Title
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: description
    name: Description
    type: text
    helpText: ''
    typeConfig:
      required: false
      multiline: true
      linesCount: '10'
    localizable: true
  - id: highlightText
    name: Highlight Text
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: image
    name: Image
    type: asset
    helpText: ''
    typeConfig:
      max: 1
      min: 0
  - id: features
    name: Features
    type: json
    helpText: ''
    typeConfig:
      schema:
        type: array
        items:
          type: string
  - id: group_primaryCta
    name: Primary CTA
    type: group
    typeConfig:
      childrenParams:
        - primaryButtonCopy
        - primaryButtonStyle
        - primaryButtonLink
        - primaryButtonAnimationType
  - id: primaryButtonCopy
    name: Primary Button Copy
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: primaryButtonStyle
    name: Primary Button Style
    type: tp-button-style-parameter
    helpText: ''
    typeConfig: null
  - id: primaryButtonLink
    name: Primary Button Link
    type: link
    helpText: ''
    typeConfig: null
  - id: primaryButtonAnimationType
    name: Primary Button Animation Type
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Fade-In
          value: fadeIn
        - text: Fly-In
          value: flyIn
  - id: group_secondaryCta
    name: Secondary CTA
    type: group
    typeConfig:
      childrenParams:
        - secondaryButtonCopy
        - secondaryButtonStyle
        - secondaryButtonLink
        - secondaryButtonAnimationType
  - id: secondaryButtonCopy
    name: Secondary Button Copy
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: secondaryButtonStyle
    name: Secondary Button Style
    type: tp-button-style-parameter
    helpText: ''
    typeConfig: null
  - id: secondaryButtonLink
    name: Secondary Button Link
    type: link
    helpText: ''
    typeConfig: null
  - id: secondaryButtonAnimationType
    name: Secondary Button Animation Type
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Fade-In
          value: fadeIn
        - text: Fly-In
          value: flyIn
  - id: group_imageSettings
    name: Image Settings
    type: group
    typeConfig:
      collapsed: true
      childrenParams:
        - objectFit
        - overlayColor
        - overlayOpacity
  - id: objectFit
    name: Object Fit
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Contain
          value: contain
        - text: Cover
          value: cover
        - text: Fill
          value: fill
        - text: None
          value: none
  - id: overlayColor
    name: Overlay Color
    type: tp-color-style-parameter
    helpText: ''
    typeConfig: null
  - id: overlayOpacity
    name: Overlay Opacity
    type: tp-slider-parameter
    helpText: ''
    typeConfig:
      step: 10
      type: steps
      unit: px
      units: '%'
      options: []
      maxValue: 100
      minValue: 0
  - id: group_presentationSettings
    name: Presentation Settings
    type: group
    typeConfig:
      collapsed: true
      childrenParams:
        - fullHeight
  - id: fullHeight
    name: Full Height
    type: checkbox
    helpText: ''
    typeConfig: null
  - id: group_animationSettings
    name: Animation Settings
    type: group
    typeConfig:
      collapsed: true
      childrenParams:
        - animationType
        - duration
        - delay
        - animationOrder
        - animationPreview
  - id: animationType
    name: Animation Type
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Fade-In
          value: fadeIn
        - text: Fly-In
          value: flyIn
  - id: duration
    name: Duration
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: Slow
          value: slow
        - text: Medium
          value: medium
        - text: Fast
          value: fast
  - id: delay
    name: Delay
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: None
          value: none
        - text: Short (250ms)
          value: short
        - text: Medium (500ms)
          value: medium
        - text: Long (1000ms)
          value: long
  - id: animationOrder
    name: Animation Order
    type: select
    helpText: ''
    typeConfig:
      options:
        - text: All at once (default)
          value: allAtOnce
        - text: One by one
          value: oneByOne
  - id: animationPreview
    name: Animation Preview
    type: tp-play-animation-parameter
    helpText: ''
    typeConfig: null
categoryId: 2da8c924-14d5-470b-9fe4-1e56521551e5
previewImageUrl: >-
  https://res.cloudinary.com/uniform-demos/image/upload/v1/preview-images/UniformTheme/Product_Info_preview_image
useTeamPermissions: true
slots: []
titleParameter: title
canBeComposition: false
created: '2023-09-04T19:16:21.62694+00:00'
updated: '2023-12-27T08:58:27.252107+00:00'
